#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
 <<EOF
DROP TABLE Admin CASCADE CONSTRAINTS;
DROP TABLE RentalStoreBranch CASCADE CONSTRAINTS;
DROP TABLE Booking CASCADE CONSTRAINTS;
DROP TABLE PartTime CASCADE CONSTRAINTS;
DROP TABLE FullTime CASCADE CONSTRAINTS;
DROP TABLE DriversLicense CASCADE CONSTRAINTS;
DROP TABLE Discount CASCADE CONSTRAINTS;
DROP TABLE Bill CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Rental CASCADE CONSTRAINTS;
DROP TABLE Liability CASCADE CONSTRAINTS;
DROP TABLE Car CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
exit;
EOF
