#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 “n88ahmed/10295409@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
DROP TABLE Admin CASCADE CONSTRAINTS;
DROP TABLE RentalStoreBranch CASCADE CONSTRAINTS;
DROP TABLE Booking CASCADE CONSTRAINTS;
DROP TABLE PartTime CASCADE CONSTRAINTS;
DROP TABLE FullTime CASCADE CONSTRAINTS;
DROP TABLE DriversLicense CASCADE CONSTRAINTS;
DROP TABLE Discount CASCADE CONSTRAINTS;
DROP TABLE Bill CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Rental CASCADE CONSTRAINTS;
DROP TABLE Liability CASCADE CONSTRAINTS;
DROP TABLE Car CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
exit;
EOF